### ISSUE TITLE
AttributeError when setting the named result of a ParsedResults instance

### ISSUE THREAD

**Issue by elespike** [pyparsing/pyparsing#325]
Hello,

The following script fails with pyparsing 3.0.3 (python 3.9.2):
```pycon
>>> KW = CaselessKeyword('ipsum').setResultsName('ipsum')
>>> matches = list(KW.scanString('lorem ipsum dolor si amet'))
>>> matches[0][0]
ParseResults(['ipsum'], {'ipsum': 'ipsum'})
>>> matches[0][0].ipsum  # attribute getter is ok
'ipsum'
>>> matches[0][0]['ipsum'] = 'iiipsum'  # key setter is ok
>>> matches[0][0].ipsum
'iiipsum'
>>> matches[0][0].ipsum = 'oops'  # attribute setter fails even though attribute getter works
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ParseResults' object has no attribute 'ipsum'
```

The same script works with pyparsing 2.4.7.

**Comment by elespike** [comment]
Perfect, thanks so much for the detailed explanation! =)
