### ISSUE TITLE
PyParsing 3.0.6 and 3.0.7 could not be imported in Python3.6 < 3.6.8

### ISSUE THREAD

**Issue by USSX-Hares** [pyparsing/pyparsing#366]
### Environment:
 - OS: Windows 7 x64
 - Python Version: Python 3.6.0
 - PyParsing versions: 3.0.5, 3.0.6, 3.0.7

Somehow someway the new `__version__` field from 3.0.6 is not accessible in 3.6 Python.
Works on Python 3.8, did not test on other versions.

#### 3.0.5
```python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)] on win32
>>> import pyparsing
>>> print(pyparsing.__version__)
3.0.5
```

#### 3.0.6
```python
>>> import pyparsing
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2020.2.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\git\gitlab\libraries\dataclasses-config\.venv-36\lib\site-packages\pyparsing\__init__.py", line 130, in <module>
    __version__ = __version_info__.__version__
AttributeError: 'version_info' object has no attribute '__version__'
```

#### 3.0.7
```python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)] on win32
>>> import pyparsing
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2020.2.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\git\gitlab\libraries\dataclasses-config\.venv-36\lib\site-packages\pyparsing\__init__.py", line 130, in <module>
    __version__ = __version_info__.__version__
AttributeError: 'version_info' object has no attribute '__version__'
```

**Comment by ptmcg** [comment]
Can you upgrade to Python 3.6.8? I don't have 3.6.0 installed, but I do have 3.6.8, and it does not have this problem.

Tested on WIndows 10.

```
>>> import sys
>>> sys.version
'3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]'
>>> import pyparsing as pp
>>> pp.__version__
'3.0.7'
```

**Comment by USSX-Hares** [comment]
Confirmed:
 * Works on Python 3.6.8
 * Does not work on Python 3.6.0
(Tested on both versions)

**Comment by ptmcg** [comment]
Pyparsing uses `typing.NamedTuple` to define the structure of the `__version__` tuple. NamedTuple received some fixes in 3.6.6 (https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-6-release-candidate-1), which may be part of the issue.

**Comment by ptmcg** [comment]
pyproject.toml modified in latest 3.0.8 release
